### ISSUE TITLE
Claim package on Openbase

### ISSUE THREAD

**Issue by tevko** [bendrucker/aws-sdk-js-v3-rds-signer#1]
This is a really great tool and I'd love to see more people take advantage of it - claiming on openbase would really increase views and usage, and hopefully get AWS on implementing this functionality in V3 of their SDK

https://openbase.com/js/aws-sdk-js-v3-rds-signer

**Comment by bendrucker** [comment]
Never heard of it, are you affiliated?

**Comment by tevko** [comment]
Yes, I'm a dev advocate for openbase. I had to connect to an RDS managed DB yesterday and needed to create a signed token - luckily found your repo to do it and figured I'd reach out to see if you were interested in claiming your package since it worked so well for me.

Happy to explain more on openbase if you'd like, feel free to DM on twitter @TimEvko

**Comment by bendrucker** [comment]
Ok, I signed up. As a package consumer it looks neat but it's hard to see what benefit I get as a maintainer of lots of small packages like this. If you want to share more feel free to email me at address in my profile.
