### ISSUE TITLE
Official Amazon implementation

### ISSUE THREAD

**Issue by Tilogorn** [bendrucker/aws-sdk-js-v3-rds-signer#2]
>  If/when this functionality is included natively in the SDK, this package will be deprecated in favor of the official Amazon implementation.

I used your tool for many month now but checking by accident seems that AWS has delivered: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_rds_signer.html

Cannot confirm functionality right now but should be able to do so next week.

**Comment by Tilogorn** [comment]
It's indeed a 1:1 replacement, matching your API completely (at least for my options). Thank you for your temp solution!

**Comment by bendrucker** [comment]
https://github.com/bendrucker/aws-sdk-js-v3-rds-signer/blob/14a0af2d569c6998eacb17eabb06fa76d4b5faef/index.d.ts#L8-L14

vs.

https://github.com/aws/aws-sdk-js-v3/blob/b58511abde2b1b2edddc72a2234c223644c726ca/packages/rds-signer/src/Signer.ts#L14-L39

They made `hostname` and `port` required (sensible) and offer the ability to override the hashing function. 

All valid usages of this package will work. Typescript users will get a compile-time error if `hostname` or `port` are unset. This was never going to produce a valid auth token anyway, so what was a runtime error with this package would be compile-time with Amazon's.
